#!/usr/bin/env bash
# post-triage-log.sh
# Triggered via PostToolUse hook after Gmail MCP tool calls.
# Appends a structured entry to logs/weekly-log.md.

set -euo pipefail

LOG_FILE="$(pwd)/logs/weekly-log.md"
DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H:%M")
WEEK=$(date +"%Y-W%V")

# Create logs dir and file if they don't exist
mkdir -p "$(dirname "$LOG_FILE")"

if [ ! -f "$LOG_FILE" ]; then
  echo "# Weekly Triage Log" > "$LOG_FILE"
  echo "" >> "$LOG_FILE"
  echo "_Auto-generated by post-triage-log hook. Do not edit manually._" >> "$LOG_FILE"
  echo "" >> "$LOG_FILE"
fi

# Check if a section for this week already exists
if ! grep -q "## Week: $WEEK" "$LOG_FILE" 2>/dev/null; then
  echo "" >> "$LOG_FILE"
  echo "## Week: $WEEK" >> "$LOG_FILE"
  echo "" >> "$LOG_FILE"
fi

# Append today's triage entry (Claude injects summary via stdin from hook)
# The hook runner passes Claude's last response as stdin when type=command
SUMMARY=""
if [ -t 0 ]; then
  # No stdin (running manually) — write a placeholder
  SUMMARY="(no summary captured — run via Claude hook for full output)"
else
  # Read Claude's triage output from stdin (first 800 chars to keep log lean)
  SUMMARY=$(cat | head -c 800)
fi

cat >> "$LOG_FILE" << EOF

### $DATE — $TIME

$SUMMARY

---
EOF

echo "Triage log updated: $LOG_FILE"
