#!/usr/bin/env bash
# post-triage-log.sh
# Works as both PostToolUse and Stop hook.
#
# PostToolUse: receives {session_id, tool_name, ...} — finds transcript via session_id
# Stop:        receives {transcript_path, ...}        — uses path directly

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_FILE="$PROJECT_ROOT/logs/weekly-log.md"
WEEK=$(date +"%Y-W%V")
DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H:%M")

DEBUG_LOG="$PROJECT_ROOT/logs/hook-debug.log"
mkdir -p "$PROJECT_ROOT/logs"

log() { echo "[$(date '+%H:%M:%S')] $*" >> "$DEBUG_LOG"; }

INPUT=$(cat 2>/dev/null || true)
log "Hook fired. Input: $INPUT"

# Try to get transcript_path directly (Stop hook gives this)
TRANSCRIPT=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('transcript_path', ''))
except:
    print('')
" 2>/dev/null || echo "")
log "transcript_path from payload: '$TRANSCRIPT'"

# If no transcript_path, look it up via session_id (PostToolUse gives session_id)
if [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ]; then
    SESSION_ID=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d.get('session_id', ''))
except:
    print('')
" 2>/dev/null || echo "")
    log "session_id: '$SESSION_ID'"

    if [ -n "$SESSION_ID" ]; then
        TRANSCRIPT=$(find ~/.claude/projects -name "${SESSION_ID}.jsonl" 2>/dev/null | head -1)
        log "transcript found via session_id: '$TRANSCRIPT'"
    fi
fi

if [ -z "$TRANSCRIPT" ] || [ ! -f "$TRANSCRIPT" ]; then
    log "No transcript found — exiting."
    exit 0
fi
log "Using transcript: $TRANSCRIPT"

# First: check if last_assistant_message in the Stop hook payload contains triage content
TRIAGE=$(echo "$INPUT" | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    msg = d.get('last_assistant_message', '')
    if 'Morning Triage' in msg:
        print(msg)
except:
    pass
" 2>/dev/null || echo "")

# Fallback: scan the JSONL transcript (works for PostToolUse where last_assistant_message isn't available)
if [ -z "$TRIAGE" ] && [ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ]; then
    log "last_assistant_message didn't have triage — scanning transcript."
    TRIAGE=$(python3 - "$TRANSCRIPT" <<'EOF'
import sys, json

transcript_path = sys.argv[1]
triage_content = None

try:
    with open(transcript_path) as f:
        for line in f:
            try:
                entry = json.loads(line.strip())
                # VSCode extension wraps message under a 'message' key
                msg = entry.get('message', entry)
                if msg.get('role') == 'assistant':
                    content = msg.get('content', '')
                    if isinstance(content, list):
                        for block in content:
                            if isinstance(block, dict) and block.get('type') == 'text':
                                text = block.get('text', '')
                                if 'Morning Triage' in text:
                                    triage_content = text
                    elif isinstance(content, str) and 'Morning Triage' in content:
                        triage_content = content
            except:
                continue
except:
    pass

if triage_content:
    print(triage_content)
EOF
)
fi

if [ -z "$TRIAGE" ]; then
    log "No triage content found in transcript — exiting."
    exit 0
fi
log "Triage content found (${#TRIAGE} chars). Writing to log."

mkdir -p "$PROJECT_ROOT/logs"

if [ ! -f "$LOG_FILE" ]; then
    printf "# Weekly Triage Log\n\n_Auto-generated by post-triage-log hook._\n\n" > "$LOG_FILE"
fi

if ! grep -q "## Week: $WEEK" "$LOG_FILE" 2>/dev/null; then
    printf "\n## Week: $WEEK\n\n" >> "$LOG_FILE"
fi

# Skip if this date+time entry already exists (PostToolUse fires repeatedly)
ENTRY_HEADER="### $DATE — $TIME"
if grep -qF "$ENTRY_HEADER" "$LOG_FILE" 2>/dev/null; then
    exit 0
fi

printf "\n### %s — %s\n\n%s\n\n---\n" "$DATE" "$TIME" "$TRIAGE" >> "$LOG_FILE"
log "Done. Entry written: $ENTRY_HEADER"
echo "Triage logged to $LOG_FILE"
