#!/usr/bin/env bash
# post-triage-log.sh
# Triggered via PostToolUse hook after Gmail MCP tool calls.
# Appends a timestamped entry to logs/weekly-log.md.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_FILE="$PROJECT_ROOT/logs/weekly-log.md"
DATE=$(date +"%Y-%m-%d")
TIME=$(date +"%H:%M")
WEEK=$(date +"%Y-W%V")

# Read JSON payload from Claude Code (PostToolUse passes tool info via stdin)
INPUT=$(cat 2>/dev/null || true)
TOOL_NAME=$(echo "$INPUT" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name','unknown'))" 2>/dev/null || echo "mcp__gmail")

mkdir -p "$PROJECT_ROOT/logs"

if [ ! -f "$LOG_FILE" ]; then
  printf "# Weekly Triage Log\n\n_Auto-generated by post-triage-log hook._\n\n" > "$LOG_FILE"
fi

if ! grep -q "## Week: $WEEK" "$LOG_FILE" 2>/dev/null; then
  printf "\n## Week: $WEEK\n\n" >> "$LOG_FILE"
fi

printf "\n### %s — %s\nTool: %s\n\n---\n" "$DATE" "$TIME" "$TOOL_NAME" >> "$LOG_FILE"

echo "Triage log updated: $LOG_FILE"
